### ISSUE TITLE
sdc-migrate fails with mongodb docker container

### ISSUE THREAD

**Issue by teutat3s** [joyent/sdc-headnode#19]
I'm trying to migrate a docker container on TritonDataCenter with `sdc-migrate`
The container uses a slightly modified image of https://github.com/autopilotpattern/mongodb

I get the following error at the `migration-begin` phase, in the initial `provision` job:

```
cnapi.wait_task
vmadm exited with code: 1: 
...faa7-bbc4b3d043fe.zonecfg.lockfile","level":20,"ret":{"stderr":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe: No such zone configured\n","stdout":"Use 'create' to begin configuring a new zone.\n"},"msg":"zonecfg ran successfully","time":"2019-09-27T17:02:36.531Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":20,"stdout":"Use 'create' to begin configuring a new zone.\n","stderr":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe: No such zone configured\n","msg":"modified zonecfg","time":"2019-09-27T17:02:36.531Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","client":"VM.js createZone (a545398d-7bdb-ea9a-faa7-bbc4b3d043fe)","level":20,"obj":{"type":"create","uuid":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe"},"msg":"vminfod watchForEvent matched event","time":"2019-09-27T17:02:36.674Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","client":"VM.js createZone (a545398d-7bdb-ea9a-faa7-bbc4b3d043fe)","level":20,"msg":"vminfod event stream stopped","time":"2019-09-27T17:02:36.674Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":30,"evt":{"args":{},"ph":"b","name":"install-zone"},"msg":"","time":"2019-09-27T17:02:36.676Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone.load","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":30,"evt":{"args":{},"ph":"b","name":"load"},"msg":"","time":"2019-09-27T17:02:36.677Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone.load","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":20,"msg":"getVmobj loading using vminfod","time":"2019-09-27T17:02:36.677Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone.load","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":30,"evt":{"args":{"result":0},"ph":"e","name":"load"},"msg":"","time":"2019-09-27T17:02:36.679Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","client":"VM.js installZone zoneadm (a545398d-7bdb-ea9a-faa7-bbc4b3d043fe)","level":20,"msg":"vminfod event stream ready - took 0.001727744s (1.73ms)","time":"2019-09-27T17:02:36.682Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","client":"VM.js installZone zoneadm (a545398d-7bdb-ea9a-faa7-bbc4b3d043fe)","level":20,"obj":{"uuid":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","vm":{"zone_state":"installed","zfs_filesystem":"zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","zpool":"zones","zonepath":"/zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe"}},"opts":{"timeout":60000,"catchErrors":true,"teardown":true},"msg":"vminfod watchForEvent created","time":"2019-09-27T17:02:36.682Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone.zoneadm-install","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":30,"args":["-z","a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","install","-q","3","-t","da57712c-e555-e066-2d59-82b8db88daa0","-x","nodataset"],"cmd":"/usr/sbin/zoneadm","evt":{"name":"zoneadm-install","ph":"b"},"opts":{},"msg":"executing command","time":"2019-09-27T17:02:36.683Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone.zoneadm-install","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":30,"args":["-z","a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","install","-q","3","-t","da57712c-e555-e066-2d59-82b8db88daa0","-x","nodataset"],"cmd":"/usr/sbin/zoneadm","evt":{"name":"zoneadm-install","ph":"e","result":1},"opts":{},"msg":"executed command","time":"2019-09-27T17:02:36.743Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":50,"err":{"message":"Command failed: could not verify fs /data: could not access /zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe/volumes/9c8674d9-f116-ca0c-90a6-ed07ca65c602: No such file or directory\nzoneadm: zone a545398d-7bdb-ea9a-faa7-bbc4b3d043fe failed to verify\n","name":"Error","stack":"Error: Command failed: could not verify fs /data: could not access /zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe/volumes/9c8674d9-f116-ca0c-90a6-ed07ca65c602: No such file or directory\nzoneadm: zone a545398d-7bdb-ea9a-faa7-bbc4b3d043fe failed to verify\n\n    at ChildProcess.exithandler (child_process.js:637:15)\n    at ChildProcess.EventEmitter.emit (events.js:98:17)\n    at maybeClose (child_process.js:743:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:810:5)","code":1,"signal":null},"stdout":"","stderr":"could not verify fs /data: could not access /zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe/volumes/9c8674d9-f116-ca0c-90a6-ed07ca65c602: No such file or directory\nzoneadm: zone a545398d-7bdb-ea9a-faa7-bbc4b3d043fe failed to verify\n","msg":"zoneadm failed to install: Command failed: could not verify fs /data: could not access /zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe/volumes/9c8674d9-f116-ca0c-90a6-ed07ca65c602: No such file or directory\nzoneadm: zone a545398d-7bdb-ea9a-faa7-bbc4b3d043fe failed to verify\n","time":"2019-09-27T17:02:36.746Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","client":"VM.js installZone zoneadm (a545398d-7bdb-ea9a-faa7-bbc4b3d043fe)","level":20,"msg":"vminfod watchForEvent cancelled","time":"2019-09-27T17:02:36.746Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","client":"VM.js installZone zoneadm (a545398d-7bdb-ea9a-faa7-bbc4b3d043fe)","level":20,"msg":"vminfod event stream stopped","time":"2019-09-27T17:02:36.746Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":50,"err":{"message":"first of 1 error: Command failed: could not verify fs /data: could not access /zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe/volumes/9c8674d9-f116-ca0c-90a6-ed07ca65c602: No such file or directory\nzoneadm: zone a545398d-7bdb-ea9a-faa7-bbc4b3d043fe failed to verify\n","name":"MultiError","stack":"MultiError: first of 1 error: Command failed: could not verify fs /data: could not access /zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe/volumes/9c8674d9-f116-ca0c-90a6-ed07ca65c602: No such file or directory\nzoneadm: zone a545398d-7bdb-ea9a-faa7-bbc4b3d043fe failed to verify\n\n    at /usr/vm/node_modules/vasync/lib/vasync.js:99:14\n    at /usr/vm/node_modules/VM.js:8166:33\n    at /usr/vm/node_modules/VM.js:4175:13\n    at /usr/vm/node_modules/VM.js:427:9\n    at ChildProcess.exithandler (child_process.js:641:7)\n    at ChildProcess.EventEmitter.emit (events.js:98:17)\n    at maybeClose (child_process.js:743:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:810:5)\nCaused by: Error: Command failed: could not verify fs /data: could not access /zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe/volumes/9c8674d9-f116-ca0c-90a6-ed07ca65c602: No such file or directory\nzoneadm: zone a545398d-7bdb-ea9a-faa7-bbc4b3d043fe failed to verify\n\n    at ChildProcess.exithandler (child_process.js:637:15)\n    at ChildProcess.EventEmitter.emit (events.js:98:17)\n    at maybeClose (child_process.js:743:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:810:5)"},"msg":"installZone error","time":"2019-09-27T17:02:36.750Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone.install-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":30,"evt":{"args":{"result":-1},"ph":"e","name":"install-zone"},"msg":"","time":"2019-09-27T17:02:36.750Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create.create-zone","action":"create","vm":"a545398d-7bdb-ea9a-faa7-bbc4b3d043fe","level":30,"evt":{"args":{"result":-1},"ph":"e","name":"create-zone"},"msg":"","time":"2019-09-27T17:02:36.750Z","v":0}
{"name":"vmadm","req_id":"b609e7a4-4ccb-4be5-a762-23b7d53d628d","hostname":"cn04","pid":50880,"stack":"vmadm.create","level":30,"evt":{"args":{"result":-1},"ph":"e","name":"create"},"msg":"","time":"2019-09-27T17:02:36.750Z","v":0}
first of 1 error: Command failed: could not verify fs /data: could not access /zones/a545398d-7bdb-ea9a-faa7-bbc4b3d043fe/volumes/9c8674d9-f116-ca0c-90a6-ed07ca65c602: No such file or directory
zoneadm: zone a545398d-7bdb-ea9a-faa7-bbc4b3d043fe failed to verify
```

I don't know the background of these `volumes/` folders because some docker container seem to have it, others don't (`autopilotpattern/consul` has them too, `autopilotpattern/nginx` doesn't).

@twhiteman 
Is migrating docker containers not implemented yet?

**Comment by twhiteman** [comment]
Migration of docker containers is (meant to be) supported. I believe there is an error here trying to move/mount the volume that the container is using - I will need to look into that.

Was this the consul instance you were trying to migrate (I think consul defines a VOLUME in the image)?

**Comment by teutat3s** [comment]
Yes, one was based on the consul image, the other on the mongodb one

**Comment by twhiteman** [comment]
Oh right, MongoDB uses a volume too:
https://github.com/docker-library/mongo/blob/14ec2439d7d1b81ea2fe9091d60dc59ac3eaefe0/3.4/Dockerfile#L98

**Comment by twhiteman** [comment]
This should be fixed by these commits:

- https://github.com/joyent/sdc-cn-agent/commit/fb43ab50b4f982373e1ea3c34e7f9a4e37e1f15c
- https://github.com/joyent/sdc-vmapi/commit/800401b62928d42712ffe6e2e24bea11df7623ab
